---
- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: yes
  when: update_all_packages | bool

- name: Install common packages
  ansible.builtin.dnf:
    name:
      - git
      - wget
      - curl
      - unzip
      - tar
      - java-17-openjdk
      - java-17-openjdk-devel
      - python3
      - python3-pip
    state: present

- name: Set JAVA_HOME
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: "JAVA_HOME={{ java_home }}"
    create: yes
